{
    'name': 'Family Finance',
    'version': '17.0.1.3.0',
    'category': 'Productivity',
    'summary': 'Grocery bills, income and savings plans for the family',
    'author': 'Ros',
    'license': 'LGPL-3',
    'depends': ['family_tracker'],
    'data': [
        'security/ir.model.access.csv',
        'security/finance_security.xml',
        'views/finance_bill_views.xml',
        'views/finance_housing_views.xml',
        'views/finance_expense_views.xml',
        'views/finance_income_views.xml',
        'views/finance_saving_views.xml',
        'views/finance_budget_views.xml',
        'views/finance_plan_views.xml',
        'views/finance_overview_action.xml',
        'views/finance_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'family_finance/static/src/js/finance_app.js',
            'family_finance/static/src/js/finance_dialogs.js',
            'family_finance/static/src/js/finance_views.js',
            'family_finance/static/src/js/finance_overview.js',
            'family_finance/static/src/js/finance_savings.js',
            'family_finance/static/src/js/finance_expenses.js',
            'family_finance/static/src/xml/finance_dialogs.xml',
            'family_finance/static/src/xml/finance_overview.xml',
            'family_finance/static/src/xml/finance_savings.xml',
            'family_finance/static/src/xml/finance_expenses.xml',
            'family_finance/static/src/scss/finance.scss',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
}
