{
    'name': 'Family Daily Tracker',
    'version': '17.0.1.0.0',
    'category': 'Productivity',
    'summary': 'Track daily family tasks and routines',
    'author': 'Ros',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'uom'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/groceries_product_views.xml',
        'views/groceries_stock_entry_views.xml',
        'views/groceries_barcode_scanner_action.xml',
        'views/groceries_menus.xml',
        'views/family_home.xml',
        'views/webclient_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'family_tracker/static/src/js/family_apps.js',
            'family_tracker/static/src/js/family_apps_registry.js',
            'family_tracker/static/src/js/family_theme.js',
            'family_tracker/static/src/js/family_bottom_nav.js',
            'family_tracker/static/src/js/family_home.js',
            'family_tracker/static/src/js/groceries_barcode_scanner.js',
            'family_tracker/static/src/js/groceries_form_leave.js',
            'family_tracker/static/src/xml/family_bottom_nav.xml',
            'family_tracker/static/src/xml/family_home.xml',
            'family_tracker/static/src/xml/groceries_barcode_scanner.xml',
            'family_tracker/static/src/scss/family_theme.scss',
            'family_tracker/static/src/scss/groceries.scss',
        ],
    },
    'installable': True,
    'application': True,
}
